### DISCUSSION TITLE
Help regarding setup of wasm32-unknown-emscripten static library that can be linked to a cpp project.

### DISCUSSION THREAD

**Discussion by nnstanusic** [gfx-rs/wgpu#6979] [Q&A]
Hello and thank you for taking the time,

I'm attempting to create a small cross platform rendering static library using Rust and wgpu. The library would then be linked i into an existing C++. The API of the lib is just a Init and Render function hidden behind extern "C" for now.  

So far, I've managed to make it work on Windows with SDL where I pass the HWND through raw_window_handle.  💪

When calling the generated emscripten wasm. During creation of the wgpu::Instance i get an error that no backend could be found. 
I haven't reached creation of a surface linking it to a canvas yet.

Currently the whole static library is just the [learn wgpu](https://sotrh.github.io/learn-wgpu/) sample and the error happens here: 

```rust
let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            #[cfg(not(target_arch = "wasm32"))]
            backends: wgpu::Backends::PRIMARY,
            #[cfg(target_arch = "wasm32")]
            backends: wgpu::Backends::all(),
            ..Default::default()
        });
```

No backend could be found.

Does anybody have any advice on how to proceed? 

<details>
  <summary>This is the content of my Cargo.toml for now. </summary>
  
```toml
[lib]
crate-type = ["rlib", "staticlib"]

[build-dependencies]
anyhow = "1.0"
glob = "0.3"
cbindgen = "0.28.0"

[dependencies]
cfg-if = "1"
pollster = "0.3"
wgpu = "22.0"
bytemuck = { version = "1.16", features = ["derive"] }
cgmath = "0.18"
tobj = { version = "3.2", default-features = false, features = ["async"] }
raw-window-handle = "0.6.2"
log = "0.4"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "22.0", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }
reqwest = { version = "0.11" }
```

</details>

<details>
  <summary>CMakeLists.txt for linking into emscripten</summary>

```cmake
cmake_minimum_required(VERSION 3.20)

set(CMAKE_CXX_STANDARD 17)

project(emscripten_canvas_cpp VERSION 0.1)

find_package(render_lib REQUIRED)
add_executable(emscripten_canvas_cpp main.cpp)
target_link_libraries(emscripten_canvas_cpp PRIVATE  
    render_lib::render_lib  ##assume that static lib link correctly and headers are present
)

target_link_options(emscripten_canvas_cpp PUBLIC 
    -lembind
    -sMAX_WEBGL_VERSION=2
    $<IF:$<CONFIG:Release>,-O3,-O0>
    $<IF:$<CONFIG:Release>,-g0,-g>
)
```

</details>
