### ISSUE TITLE
Error in Device::poll: GPU got stuck :(

### ISSUE THREAD

**Issue by runfalk** [gfx-rs/wgpu#1257]
**Description**
When I run a simple bevy program the screen freezes and the program eventually crashes. During the crash I get this error message `Error in Device::poll: GPU got stuck :(` (full backtrace attached).

I was unsure whether this belongs in Bevy or here, but decided to start here. Please redirect me if this is the wrong bug tracker.

**Repro steps**
I used the following piece of code:

Cargo.toml

```toml
[package]
name = "bevy-visualization"
version = "0.1.0"
authors = ["Andreas Runfalk <user@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "b17f8a4bce5551b418654fffb1fe97ff0f9852f0" }
```

main.rs

```rust
use bevy::{
    prelude::*,
    render::mesh::shape,
};

struct SpinZ;

fn rotator_system(time: Res<Time>, mut query: Query<&mut Transform, With<SpinZ>>) {
    for mut transform in query.iter_mut() {
        transform.rotation *= Quat::from_rotation_z(time.delta_seconds());
    }
}


fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands
        // Spawn cube
        .spawn(PbrBundle {
            mesh: meshes.add(Mesh::from(shape::Cube { size: 2.0 })),
            material: materials.add(StandardMaterial {
                unlit: true,
                ..Default::default()
            }),
            transform: Transform::from_xyz(0.0, 0.0, 1.0),
            ..Default::default()
        })
        .with(SpinZ)
        // spawn camera
        .spawn(PerspectiveCameraBundle {
            transform: Transform::from_xyz(5.0, 10.0, 10.0).looking_at(Vec3::default(), Vec3::Z),
            ..Default::default()
        });
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup.system())
        .add_system(rotator_system.system())
        .run();
}
```

**Expected vs observed behavior**
This is supposed to render a white cube that spins around the vertical axis. There is no lighting in the scene to the cube's surface is completely white.

What I get is a black window and a frozen screen until the program crashes.

**Extra materials**
* [cargo-tree.txt](https://github.com/gfx-rs/wgpu/files/6124592/cargo-tree.txt)
* [backtrace.log](https://github.com/gfx-rs/wgpu/files/6124596/backtrace.log)

**Platform**
* Fedora 32
* X11
* Gnome shell 3.36.7
* Nvidia Quadro P2000 (dual but only one in use)
* Proprietary NVIDIA drivers (<s>460.39</s> 460.56, both exhibit the same problem)
