### ISSUE TITLE
Cannot access dedicated graphics with wgpu from a docker container.

### ISSUE THREAD

**Issue by jmalves5** [gfx-rs/wgpu#2123]
**Description:**
Calling `request_adapter` within a docker container always returns `None`, even though `nvidia-smi` works correctly within the container. This issue only appears in machines with dedicated discrete GPUs (e.g. desktop with discrete GTX 1070) and not with integrated graphics cards (e.g. GTX 1050 in a laptop).

**Repro steps:**
Setup docker container with access to discrete GPU and call `request_adapter` from somewhere within.

**Expected vs observed behavior:**
An adapter should be returned by `request_adapter` instead of `None`.

**Comment by jmalves5** [comment]
I haven't tried any of the Ash examples. `vulkaninfo` returns:
```
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by kvark** [comment]
Yeah, this looks like a broken Vulkan setup. It was able to create an instance but not do anything useful with it.

**Comment by compiaffe** [comment]
I'm a colleague of @jmalves5 :
I just tried this in the `nvidia/vulkan:1.2.133-450` container. (prep with `xhost +local:root`)
docker-compose:
```
  ds:
    image: nvidia/vulkan:1.2.133-450
    command: vkcube
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute,utility,graphics,display]
```

vkcube works fine here.
