### ISSUE TITLE
unexpected workspace behaviour

### ISSUE THREAD

**Issue by nikchristl** [gfx-rs/wgpu#2356]
**Description**
cargo workspace creating unexpected result.

**Repro steps**

execute, ```cargo run -p hello```

workspace directory
```bash
├── Cargo.lock
├── Cargo.toml
├── hello
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── target
```

Cargo.toml
```toml
[workspace]
members = [
    "hello",
]
```

Cargo.toml
```toml
[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.12.0"
```

main.rs
```rust
use wgpu;

fn main() {
    println!("Hello, world!");
}
```
**Expected vs observed behavior**
expected to print Hello, world!,
got Error: error: could not compile `wgpu-hal` due to 452 previous errors.
runs fine, if workspace is a package

new cargo.toml file 
```toml
[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "hello",
]

[dependencies]
```
**Extra materials**
[sample.zip](https://github.com/gfx-rs/wgpu/files/7810021/sample.zip)

**Platform**
OS: windows 10,
rust: stable-x86_64-pc-windows-msvc unchanged - rustc 1.57.0 (f1edd0429 2021-11-29)
