### ISSUE TITLE
egui fails to render in browser when using Backends::GL

### ISSUE THREAD

**Issue by pierscowburn** [gfx-rs/wgpu#2573]
**Description**
I'm trying to get [egui](https://github.com/emilk/egui) running in the browser using [egui_wgpu_backend](https://github.com/hasenbanck/egui_wgpu_backend) (rather than egui's own WebGL-based browser support).

I've been able to get it running using `Backends::BROWSER_WEBGPU` in Canary and also in Firefox Nightly, which is great. I'm now trying to also get it running using `Backends::GL`, as our project uses the GL backend as a fallback until browser support for WebGPU becomes mainstream.

**Repro steps**
https://github.com/pierscowburn/egui_wgpu_failure_case contains a minimal example. The example can be run with each backend as follows:

```bash
# Run with wgpu::Backends::BROWSER_WEBGPU
RUSTFLAGS=--cfg=web_sys_unstable_apis cargo run-wasm example

# Run with wgpu::Backends::GL
cargo run-wasm example --features webgl
```

**Expected behavior**
The example should render with a green background when using either backend.

**Observed behavior**
With the `wgpu::Backends::BROWSER_WEBGPU` backend the example renders correctly with a green background.

With the `wgpu::Backends::GL` backend the example renders with a red background (the clear color is set to red),
and some WebGL errors are printed to the console.

In Canary the warning is:

```
[.WebGL-0x7015b47700] GL_INVALID_OPERATION: It is undefined behaviour to use a uniform buffer that is too small.
```

In Firefox the warnings are:

```
WebGL warning: drawElementsInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.
WebGL warning: getSyncParameter: ClientWaitSync must return TIMEOUT_EXPIRED until control has returned to the user agent's main loop.
```

**Platform**
```toml
egui = "0.16"
egui_wgpu_backend = "0.16"
egui_winit_platform = "0.13"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.56", features = [
    "console",
    "Document",
    "Element",
    "Performance",
    "Window",
]}
wgpu = "0.12.0"
winit = "0.26"
```
