### ISSUE TITLE
wgpu-hal does not compile as dependency of a edition="2018"

### ISSUE THREAD

**Issue by C0D3-M4513R** [gfx-rs/wgpu#2649]
**Description**
wgpu-hal fails to compile in my current project.
My current project consists of the hello-triange example copy/pasted as my main file.
My Cargo.toml looks like this:
```toml
[package]
name = "rust-vulkan"
version = "0.1.0"
authors = ["C0D3 M4513R <28912031+C0D3-M4513R@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12"
env_logger="0.9.0"
pollster="0.2.5"
```

**Repro steps**
See Cargo.toml here, and the hello-triangle example in this repo

**Expected vs observed behavior**
I expect, that `cargo run` at least gets to compiling my code, but here it fails before even compiling wgpu.

**Extra materials**
Compilation log:
[cargo-run.txt](https://github.com/gfx-rs/wgpu/files/8650660/cargo-run.txt)

**Platform**
Os: Windows 10, Version	10.0.19043 Build 19043
```
PS C:\Users\XXX\CLionProjects\inject\rust-vulkan> rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.60.0 (7737e0b5c 2022-04-04)`
```
target: x86_64-pc-windows-msvc

**Comment by Gordon-F** [comment]
@C0D3-M4513R Add `resolver = "2"` in your top level Cargo.toml file, this should fix all compile errors.

```toml
[package]
name = "rust-vulkan"
version = "0.1.0"
authors = ["C0D3 M4513R <28912031+C0D3-M4513R@users.noreply.github.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.12"
```
