### ISSUE TITLE
Using multiple major versions of wgpu causes linker errors

### ISSUE THREAD

**Issue by SludgePhD** [gfx-rs/wgpu#3105]
**Description**
When a binary links against both wgpu 0.13 and wgpu 0.14, a linker error is caused by one-definition-rule violations, caused by a bunch of `#[no_mangle]` functions like here: https://github.com/gfx-rs/wgpu/blob/b28a87e2984181a5eaf659850f55b1e5aa1a461c/wgpu-core/src/command/render.rs#L2111-L2112

**Repro steps**

`Cargo.toml`:
```toml
[package]
name = "double-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu14 = { version = "0.14", package = "wgpu" }
wgpu13 = { version = "0.13", package = "wgpu" }
```

`src/main.rs`:
```rust
fn main() {
    wgpu13::Instance::new(wgpu13::Backends::PRIMARY);
    wgpu14::Instance::new(wgpu14::Backends::PRIMARY);
}
```

**Expected vs observed behavior**
This should just work, ideally, since wgpu is Rust code, not C.

I'm not sure why these are marked as `#[no_mangle]` – they're called by code in `wgpu` that imports these items by name, not by linking to them through an `extern "C" { }` block. Mangling should not be a problem for that. If they're intended to also be used by C code, perhaps the FFI wrapper should be moved to a small shim crate?
