### ISSUE TITLE
`wgpu-hal` unable to create adapter on Emscripten + SDL2

### ISSUE THREAD

**Issue by Zentendo** [gfx-rs/wgpu#3247]
The browser main thread will hang on `<hal::api::Gles as hal::Api>::Adapter::new_external()` and `video.gl_get_proc_address(name) as *const _` despite making it to the last GL command `glWaitSync`, without returning an error.

```rust
extern crate wgpu_hal as hal;

fn main() {
    env_logger::init();

    println!("Initializing external GL context and SDL");
    let sdl = sdl2::init().unwrap();
    let video = sdl.video().unwrap();
    let window = video.window("Legend Of Worlds", 640, 400)
        .opengl()
        .resizable()
        .build()
        .unwrap();
    window.gl_create_context().unwrap();

    println!("Hooking up to wgpu-hal");
    let exposed = unsafe {
        <hal::api::Gles as hal::Api>::Adapter::new_external(|name| {
            video.gl_get_proc_address(name) as *const _
        })
        .expect("GL adapter can't be initialized")
    };
    
    use hal::{Adapter as _, CommandEncoder as _, Device as _, Queue as _};

    let mut od = unsafe {
        exposed
            .adapter
            .open(wgt::Features::empty(), &wgt::Limits::downlevel_defaults())
    }
    .unwrap();

    let format = wgt::TextureFormat::Rgba8UnormSrgb;
    let texture = <hal::api::Gles as hal::Api>::Texture::default_framebuffer(format);
    let view = unsafe {
        od.device
            .create_texture_view(
                &texture,
                &hal::TextureViewDescriptor {
                    label: None,
                    format,
                    dimension: wgt::TextureViewDimension::D2,
                    usage: hal::TextureUses::COLOR_TARGET,
                    range: wgt::ImageSubresourceRange::default(),
                },
            )
            .unwrap()
    };

    println!("Filling the screen");
    let mut encoder = unsafe {
        od.device
            .create_command_encoder(&hal::CommandEncoderDescriptor {
                label: None,
                queue: &od.queue,
            })
            .unwrap()
    };
    let rp_desc = hal::RenderPassDescriptor {
        label: None,
        extent: wgt::Extent3d {
            width: 640,
            height: 400,
            depth_or_array_layers: 1,
        },
        sample_count: 1,
        color_attachments: &[Some(hal::ColorAttachment {
            target: hal::Attachment {
                view: &view,
                usage: hal::TextureUses::COLOR_TARGET,
            },
            resolve_target: None,
            ops: hal::AttachmentOps::STORE,
            clear_value: wgt::Color::BLUE,
        })],
        depth_stencil_attachment: None,
        multiview: None,
    };
    unsafe {
        encoder.begin_encoding(None).unwrap();
        encoder.begin_render_pass(&rp_desc);
        encoder.end_render_pass();
        let cmd_buf = encoder.end_encoding().unwrap();
        od.queue.submit(&[&cmd_buf], None).unwrap();
    }
}
```

**Comment by jimblandy** [comment]
Are there any messages in the console?

**Comment by jimblandy** [comment]
Wondering if this is related to #3245.

**Comment by Zentendo** [comment]
@jimblandy Nope, no errors in the console. Also, it's not related to https://github.com/gfx-rs/wgpu/issues/3245, I had to revert back to version `0.13` to avoid that error.

Here is my `Cargo.toml`.

```toml
[dependencies]
sdl2 = { version="0.35.2", default-features = false, features = ["unsafe_textures", "image"] }
wgpu = { version="0.13", features = ["webgl", "emscripten"] }
wgpu-hal = { version="0.13", features = ["emscripten"] }
env_logger = "0.8"

[dependencies.wgt]
package = "wgpu-types"
version = "0.13"
```

**Comment by Zentendo** [comment]
This appears to be breaking at  `glow/src/native.rs` on this line.

```rust
let raw: native_gl::GlFns =
    native_gl::GlFns::load_with(|p: *const std::os::raw::c_char| {
        let c_str = std::ffi::CStr::from_ptr(p);
        println!("{}", c_str.to_str().unwrap());
        loader_function(c_str) as *mut std::os::raw::c_void
    });
// Retrieve and parse `GL_VERSION`
let raw_string = raw.GetString(VERSION);
```

Glow by itself however works with SDL + Emscripten perfectly fine without WGPU.

```rust
let (gl, shader_version, window, mut events_loop, _context) = {
    let sdl = sdl2::init().unwrap();
    let video = sdl.video().unwrap();
    let gl_attr = video.gl_attr();
    let window = video
        .window("Hello triangle!", 1024, 769)
        .opengl()
        .resizable()
        .build()
        .unwrap();
    let gl_context = window.gl_create_context().unwrap();
    let gl = unsafe { glow::Context::from_loader_function(|s| video.gl_get_proc_address(s) as *const _) };
    let event_loop = sdl.event_pump().unwrap();
    (gl, "#version 300 es", window, event_loop, gl_context)
};

unsafe {
    let vertex_array = gl
        .create_vertex_array()
        .expect("Cannot create vertex array");
    gl.bind_vertex_array(Some(vertex_array));

    let program = gl.create_program().expect("Cannot create program");

    let (vertex_shader_source, fragment_shader_source) = (
        r#"const vec2 verts[3] = vec2[3](
            vec2(0.5f, 1.0f),
            vec2(0.0f, 0.0f),
            vec2(1.0f, 0.0f)
        );
        out vec2 vert;
        void main() {
            vert = verts[gl_VertexID];
            gl_Position = vec4(vert - 0.5, 0.0, 1.0);
        }"#,
        r#"precision mediump float;
        in vec2 vert;
        out vec4 color;
        void main() {
            color = vec4(vert, 0.5, 1.0);
        }"#,
    );

    let shader_sources = [
        (glow::VERTEX_SHADER, vertex_shader_source),
        (glow::FRAGMENT_SHADER, fragment_shader_source),
    ];

    let shader_sources = [
        (glow::VERTEX_SHADER, vertex_shader_source),
        (glow::FRAGMENT_SHADER, fragment_shader_source),
    ];

    let mut shaders = Vec::with_capacity(shader_sources.len());


    for (shader_type, shader_source) in shader_sources.iter() {
        let shader = gl
            .create_shader(*shader_type)
            .expect("Cannot create shader");
        gl.shader_source(shader, &format!("{}\n{}", shader_version, shader_source));
        gl.compile_shader(shader);
        if !gl.get_shader_compile_status(shader) {
            panic!("{}", gl.get_shader_info_log(shader));
        }
        gl.attach_shader(program, shader);
        shaders.push(shader);
    }

    gl.link_program(program);
    if !gl.get_program_link_status(program) {
        panic!("{}", gl.get_program_info_log(program));
    }

    for shader in shaders {
        gl.detach_shader(program, shader);
        gl.delete_shader(shader);
    }

    gl.use_program(Some(program));
    gl.clear_color(0.1, 0.2, 0.3, 1.0);
    gl.clear(glow::COLOR_BUFFER_BIT);
    gl.draw_arrays(glow::TRIANGLES, 0, 3);
    window.gl_swap_window();
}
```

**Comment by coderedart** [comment]
idk if its relevant, but with the latest wgpu and latest sdl2 master branches, it works fine for me. 

I used normal wgpu though and not the wgpu-hal thing.

**Comment by benjamin-sieffert** [comment]
@coderedart 

> idk if its relevant, but with the latest wgpu and latest sdl2 master branches, it works fine for me.
> 
> I used normal wgpu though and not the wgpu-hal thing.

Mind sharing your code? (And perhaps importantly all the emcc linker flags and wgpu feature flags used.)

I am trying to make the same combo work, but think I am hitting the issue described here, failing at `new_external`: `Cannot read properties of undefined (reading 'getParameter')`
I also wonder how to create the `wgpu::Surface` after creating the Adapter this way, if it would succeed.

The normal way of setting up, just calling `request_adapter` with the `compatible_surface` already created, only returns `None` for me.
All this is with `ERROR_ON_UNDEFINED_SYMBOLS=0` (as prescribed in the original docs for wgpu-hal) to get emcc to link the thing at all. Otherwise refuses because it cannot resolve `eglGetPlatformDisplay` and `eglCreatePlatformWindowSurface`.

**Comment by coderedart** [comment]
@benjamin-sieffert 

https://github.com/coderedart/etk/blob/master/crates/egui_window_sdl2/README.md gives a rough overview of what i did. And you need to enable the `webgl` feature of wgpu.

copy pasting it here in case the link ever changes.

These are the emscripten flags i used. 
```toml
# inside .cargo/config.toml of your project root
[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_GLFW=3", # for glfw support. 
    # "-C",
    # "link-arg=-s",
    # "-C",
    # "link-arg=FULL_ES2",# for opengl es 2 emulation
    # "-C",
    # "link-arg=-s",
    # "-C",
    # "link-arg=FULL_ES3", # for opengl es 3 emulation
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL=2", # for sdl2. 
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MAX_WEBGL_VERSION=2 ", # to make sure that webgl2 is enabled. 
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MIN_WEBGL_VERSION=2", # to disable webgl1 completely, and use webgl2 exclusively. 
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1", # i don't even remember why i have this :D.
]
```

The html file contents. Don't forget the `data-raw-handle` property on canvas, as that is what wgpu uses from sdl2 as the `raw-window-handle`
```html
<!DOCTYPE html>
<html>
  <body>
    <canvas data-raw-handle="1" id="canvas"></canvas>
    <!-- you need this script to actually let sdl2 library find the canvas for backing its window -->
    <script type="text/javascript">
      var Module = {
        canvas: (function () {
          // this is how we provide a canvas to our sdl2
          return document.getElementById("canvas");
        })(),
      };
    </script>
    <!-- the above scrit MUST BE loaded before the below generated by cargo. so, don't change the order of these tags -->
    <script src="rust-sdl2-wasm.js"></script>
  </body>
</html>
```

Everything else is just how you would normally use wgpu with other crates. You use the raw-window-handle to create surface and continue on like any other game. 

https://github.com/coderedart/rust-sdl2-wasm is a complete example which uses the crates from https://github.com/coderedart/etk/blob/master/crates/egui_window_sdl2/README.md and https://github.com/coderedart/etk/blob/master/crates/egui_render_wgpu/Cargo.toml .
