### ISSUE TITLE
Add a default feature for wgpu that enables Vulkan & GLES on Windows & Linux

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#3514]
We currently only enable backends based on the target platform with the only exception being GLES which is always available.

We should expose a new feature flag (enabled by default) that covers the GLES and DX11 backends so that users not interested in those backends can avoid compiling them in their binaries.

Feature name ideas:
- `legacy`
- `compat` (mapping to a future WebGPU Compat; might not be the best choice since we support even lower limits/features than what WebGPU Compat is aiming for; i.e. GLES 3.1+ and DX11 FL10+)

See background for this: https://github.com/gfx-rs/wgpu/issues/1221#issuecomment-1430067962

**Comment by daxpedda** [comment]
I was recently looking into this but the first roadblock I hit is that we can't differentiate between a new `gles` crate feature and the current `angle` crate feature, both enable `wgc/gles`.

A solution could be to introduce target-specific features in `wgpu-core` and `wgpu-hal` that are no-op on certain platforms.
E.g. `gles-native` (no-op on MacOS) and `gles-angle` (no-op on everything but MacOS). This proposal would be similar to https://github.com/gfx-rs/wgpu/pull/3466.

I'd be happy to make a PR!

**Comment by cwfitzgerald** [comment]
I think we're moving in the direction of every backend being feature flagged. We have all the infrastructure in place, we just haven't lifted this to the wgpu level.

Distinguishing between angle and native would be useful!

**Comment by daxpedda** [comment]
So after playing around with it a bit I was so unsatisfied it doesn't make sense to me to proceed like that.
The issue basically boils down to Cargo not being able to connect crate features that activate optional dependencies to specific targets.

Introducing `gles-native` and `gles-angle` we can use `cfg`s to guard code to specific targets, but the dependencies these features activate will be active nevertheless. E.g. if we use `default = ["gles-native"]`, OpenGL won't work on MacOS, but the dependencies will still be present.

So the only good solution I can come up with to this problem is to create a separate crate that adds these defaults.
```toml
[package]
name = "wgpu-default-features"

# We want the wgpu-core Metal backend on macOS and iOS.
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies.wgc]
workspace = true
features = ["metal"]

# We want the wgpu-core Direct3D backends and OpenGL (via WGL) on Windows.
[target.'cfg(windows)'.dependencies.wgc]
workspace = true
features = ["dx11", "dx12", "gles"]

# We want the wgpu-core Vulkan backend on Unix (but not emscripten, macOS, iOS) and Windows.
[target.'cfg(any(windows, all(unix, not(target_os = "emscripten"), not(target_os = "ios"), not(target_os = "macos"))))'.dependencies.wgc]
workspace = true
features = ["vulkan"]

# We want the wgpu-core GLES backend on Unix (but not macOS, iOS).
[target.'cfg(all(unix, not(target_os = "ios"), not(target_os = "macos")))'.dependencies.wgc]
workspace = true
features = ["gles"]
```
And then we can use `default ["dep:wgpu-default-features"]` in `wgpu`.

Just for completeness, not actually proposing this: we could abandon default features.
