### ISSUE TITLE
wgpu passing "metal" feature to wgpu_hal on Windows

### ISSUE THREAD

**Issue by jansen44** [gfx-rs/wgpu#3688]
**Description**
There's not much to say. I'm on Windows, but can't get my program to compile because it keeps falling on the same compile_error:
```
error: Metal API enabled on non-Apple OS. If your project is not using resolver="2" in Cargo.toml, it should.
```

At first I thought that it could be because I'm using a MacOS bootcamp, but I tried on a Windows desktop and the same error happened.

My Cargo.toml looks like this:
```toml
[package]
name = "me"
version = "0.1.0"
edition = "2021"
resolver = "2" # I even added the resolver = "2" part because of the error message even though it's not necessary anymore

[dependencies]
anyhow = "1.0.70"
bytemuck = "1.13.1"
log = "0.4.17"
pollster = "0.3.0"
simple_logger = "4.1.0"
thiserror = "1.0.40"
winit = "0.28.3"
wgpu = "0.15.1"
```

I think sharing the code is irrelevant since cargo/rust can't even reach the part of compiling my own code.

**Platform**
OS: Windows 10 (MacOS Bootcamp) and Windows 11
Rustc: 1.68.2
Cargo: 1.68.2
wgpu: 0.15.1
