### ISSUE TITLE
Only `GL` Backend on WASM is allowed when `webgl` feature is enabled

### ISSUE THREAD

**Issue by JustAnotherCodemonkey** [gfx-rs/wgpu#3847]
**Description**
When the "webgl" feature is enabled for allowing the WebGL backend, creating an instance from a Backends that does not include GL causes adapter creation to fail (request_adapter returns None). Everything works flawlessly as soon as the webgl feature is removed from Cargo.toml

**Repro steps**
.cargo/config.toml
```toml
[build]
target = "wasm32-unknown-unknown"
rustflags = ["--cfg=web_sys_unstable_apis"]
```

src/main.rs
```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(main)]
async fn main() {
    console_error_panic_hook::set_once();
    console_log::init_with_level(log::Level::Debug).unwrap();

    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::BROWSER_WEBGPU,
        ..Default::default()
    });
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions::default())
        .await
        .expect("Failed to get adapter!");
}
```

Cargo.toml
```toml
[package]
name = "webgl-fail"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.18"
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
web-sys = { version = "0.3.63", features = ["Window", "Document", "HtmlCanvasElement", "console"] }
wgpu = { version = "0.16.1", features = ["webgl"] }
winit = "0.28.6"
```

index.html
```html
<html lang="en">
    <body>
    </body>
</html>
```

Using `trunk serve`, compiled on MacOS, Chrome as browser.

**Expected vs observed behavior**
I expect that the above code should not produce errors in the console as is the case without the "webgl" feature enabled. Instead, the code panics with the messages
```
webgl-fail-cce181eb966c1948.js:1261 panicked at 'Failed to get adapter!', src/main.rs:15:10

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8080/webgl-fail-cce181eb966c1948.js:1267:21)
    at console_error_panic_hook::Error::new::h6fe9c24056b7417d (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[20087]:0x7c0cf6)
    at console_error_panic_hook::hook_impl::hc562951705d82802 (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[4217]:0x55dba5)
    at console_error_panic_hook::hook::h7b5d6a78e3d12b23 (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[22759]:0x7e50a1)
    at core::ops::function::Fn::call::hb392722c2d4f035b (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[19067]:0x7b0d0e)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[8306]:0x679505)
    at std::panicking::begin_panic_handler::{{closure}}::h1e17bad04a5713a4 (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[10427]:0x6d8658)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h63adae5c31458c4b (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[25750]:0x7ffcd6)
    at rust_begin_unwind (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[16375]:0x77ea37)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (http://localhost:8080/webgl-fail-cce181eb966c1948_bg.wasm:wasm-function[21396]:0x7d32e2)
```
and
```
Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (webgl-fail-cce181eb966c1948_bg.wasm:0x7ffdde)
    at rust_panic (webgl-fail-cce181eb966c1948_bg.wasm:0x7ff20d)
    at std::panicking::rust_panic_with_hook::h85b7f6628c291e12 (webgl-fail-cce181eb966c1948_bg.wasm:0x679530)
    at std::panicking::begin_panic_handler::{{closure}}::h1e17bad04a5713a4 (webgl-fail-cce181eb966c1948_bg.wasm:0x6d8658)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h63adae5c31458c4b (webgl-fail-cce181eb966c1948_bg.wasm:0x7ffcd6)
    at rust_begin_unwind (webgl-fail-cce181eb966c1948_bg.wasm:0x77ea37)
    at core::panicking::panic_fmt::hf5c4cd929d4aaa9e (webgl-fail-cce181eb966c1948_bg.wasm:0x7d32e2)
    at core::option::expect_failed::hc36a69366777ce0b (webgl-fail-cce181eb966c1948_bg.wasm:0x7529c5)
    at core::option::Option<T>::expect::h60cbcb72b960d55a (webgl-fail-cce181eb966c1948_bg.wasm:0x6a7cf1)
    at webgl_fail::main::__wasm_bindgen_generated_main::{{closure}}::h6a4de4221b3bc9da (webgl-fail-cce181eb966c1948_bg.wasm:0x374069)
```
in the console.

**Extra materials**
Validation logs can be attached in case there are warnings and errors. (Don't know what these are but I did share the console errors)
Zip-compressed API traces and GPU captures can also land here (how does that work?)

**Platform**
MacOS 13.4, wgpu 0.16.1, Chrome 114.0.5735.90
