### ISSUE TITLE
Clean up cbindgen warnings

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#445]
Things like this:
> WARN: Skip wgpu-core::FRAME_TIMEOUT_MS - (not `pub`)
> WARN: Missing `[defines]` entry for `target_os = "ios"` in cbindgen config.
> WARN: Skip wgpu-core::VULKAN - (Unsupported expression. Cast(ExprCast { attrs: [], expr: Path(ExprPath { attrs: [], qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident(Backend), arguments: None }, Colon2, PathSegment { ident: Ident(Vulkan), arguments: None }] } }), as_token: As, ty: Path(TypePath { qself: None, path: Path { leading_colon: None, segments: [PathSegment { ident: Ident(u32), arguments: None }] } }) }))

The `[defines]` section in cbindgen TOML needs to be populated with something like:
```toml
[defines]
"target_os = ios" = "WGPU_TARGET_IOS"
"target_os = macos" = "WGPU_TARGET_MACOS"
"unix" = "WGPU_TARGET_FAMILY_UNIX"
"windows" = "WGPU_TARGET_WINDOWS"
```

And then the examples would need to set up these defines on the affected platforms. It would be nice if we could convince cbindgen to check for `WGPU_TARGET = XXX` condition instead of `#ifdef WGPU_TARGET_XXX`, just like our triangle example currently does.
