### ISSUE TITLE
Can't use Intel Vulkan on an NVIDIA Optimus laptop

### ISSUE THREAD

**Issue by melody-rs** [gfx-rs/wgpu#5047]
**Description**
I'm on an NVIDIA Optimus laptop, and I'd like to run my code on my integrated GPU (for battery life, and to test against lower end systems)

However, when trying to use `Instance::request_device`, I get this warning in my console:

`WARN  wgpu_hal::vulkan::instance] Disabling presentation on 'Intel(R) Graphics (RPL-P)' (id 0x55bbc15ef600) due to NV Optimus and Intel Mesa < v21.2`

wgpu then defaults to using my dedicated GPU instead. Trying to use my integrated GPU anyway by using `Instance::enumerate_adapters` works, but any surface I create isn't supported! 
I'm not sure what the warning means either, since I have mesa 23.2.3 installed.

**Repro steps**
I made a basic repro:
[repro.tar.gz](https://github.com/gfx-rs/wgpu/files/13907949/repro.tar.gz)

**Extra materials**
[debug_log.txt](https://github.com/gfx-rs/wgpu/files/13908036/debug_log.txt)

I'm happy to provide any additional logs if needed!

#2129 and #1215 seem relevant

**Platform**
```yml
CPU: Intel Core i9-13900H
Graphics:
  Device-1: Intel Raptor Lake-P [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: NVIDIA AD107M [GeForce RTX 4060 Max-Q / Mobile] driver: nvidia
    v: 545.29.06
  Display: x11 server: X.org v: 1.21.1.10 with: Xwayland v: 23.2.3 driver:
    X: loaded: modesetting,nvidia dri: iris gpu: i915
    resolution: 2560x1600~120Hz
  API: EGL v: 1.5 drivers: iris,kms_swrast,nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 23.1.9-manjaro1.1
    renderer: Mesa Intel Graphics (RPL-P)
Kernel: 6.5.13-7-MANJARO x86_64
```
